language: python

python:
  - 2.7
  - 3.4

sudo: required

before_install:
  - sudo apt-get install update -qq
  - sudo apt-get install install -qq libsmbclient-dev

install:
  - pip install .

script:
